//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Innotym.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> RefId { get; set; }
        public string TransType { get; set; }
        public Nullable<decimal> InitialAmount { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
        public virtual UserDetail UserDetail1 { get; set; }
    }
}
